language: python
python:
  - '2.7'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository -y ppa:gijzelaar/aartfaac
  - sudo apt-get update -qq
  - sudo ldconfig
script:
  - true
